### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by jakubdrabik** [realshadow/satis-control-panel#1]
Packagist doesn't show up any version except dev-master.

**Comment by realshadow** [comment]
I was manually deleting releases two weeks ago and Packagist was failing with constraint violations, looks like it managed to fix it by itself, since manual update was enough to pull 1.0.0 release.

Sorry about that.

I won't close this yet, if you get any weird problems during installation let me know. I am very curious if it will work on other systems out of the box

**Comment by jakubdrabik** [comment]
I've got a problem with php version. I am using PHP v5.6 and it is trying to convince me I am using v5.5 and says something about config.platform.php - I am not sure whether it is problem in my environment or there are some configuration errors in any dependency. I solved it with ignoring parametr in composer create-project command.

The problem is while I am using npm install because it shows up an error:
ERROR in ./resources/assets/typescript/helpers.tsx
(22,16): error TS2349: Cannot invoke an expression whose type lacks a call signature.

It looks like there is a syntax error in the typescript file.

**Comment by realshadow** [comment]
The problem with composer happens if he can not parse your php version correctly. Some package managers use their own version format, e.g. I have _PHP 5.6.18-1+deb.sury.org~trusty+1_ on Ubuntu  and the exact problem.

The NPM error can be safely ignored, its just a bad definition file. The error by itself does nothing

**Comment by jakubdrabik** [comment]
Yeah, it seems like it is my problem. 
Ok, I am skipping the npm error and another step is satis.json configuration. But the resources/satis.json.dist file is missing.

**Comment by jakubdrabik** [comment]
And also, an index.php file is missing.

**Comment by realshadow** [comment]
Always something missing! Added it back in version 1.0.1. Please update to that.

Index.php is not missing. The control panel is located at `http://{host}/control-panel` and the packages are then generated at `http://{host}/public` and `http://{host}/private` to distinguish between all three.

This also adds a bit more configuration options, if for example you want to only use private packages, you can change the root directory to `./public` instead of `./public/private` and have your packages generated at `http://{host}` and still have a functioning control panel.

I have added to readme as well.

**Comment by jakubdrabik** [comment]
I am getting 500 while it is trying to return view in Controller. Nothing is logged and permissions are set to 0777.

**Comment by realshadow** [comment]
You will have to take a look inside Apache/Nginx error log to see what is going on

**Comment by jakubdrabik** [comment]
The problem is, there is problem about permissions in storage dir even they
are set to 0777, I will play with server configuration, but the error is
weird.
Dne 15. 2. 2016 21:37 napsal uživatel "Lukáš Homza" <
notifications@github.com>:

**Comment by realshadow** [comment]
Can please show me the error reported?

**Comment by jakubdrabik** [comment]
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with
message 'The stream or file
"/home/jakub/www/satis/storage/logs/laravel.log" could not be opened:
failed to open stream: Permission denied' in
/home/jakub/www/satis/bootstrap/cache/compiled.php:13358\nStack trace:\n#0
/home/jakub/www/satis/bootstrap/cache/compiled.php(13296):
Monolog\Handler\StreamHandler->write(Array)\n#1
/home/jakub/www/satis/bootstrap/cache/compiled.php(13059):
Monolog\Handler\AbstractProcessingHandler->handle(Array)\n#2
/home/jakub/www/satis/bootstrap/cache/compiled.php(13155):
Monolog\Logger->addRecord(400,
Object(Symfony\Component\Debug\Exception\FatalErrorException),
Array)\n#3 /home/jakub/www/satis/bootstrap/cache/compiled.php(12872):
Monolog\Logger->error(Object(Symfony\Component\Debug\Exception\FatalErrorException),
Array)\n#4 /home/jakub/www/satis/bootstrap/cache/compiled.php(12843):
Illuminate\Log\Writer->writeLog('error',
Object(Symfony\Component\Debug\Exception\FatalErrorException),
Array)\n#5 /home/jakub/www/satis/vendor/laravel/frame in
/home/jakub/www/satis/bootstrap/cache/compiled.php on line 13358
Dne 15. 2. 2016 22:42 napsal uživatel "Lukáš Homza" <
notifications@github.com>:

**Comment by realshadow** [comment]
It looks like the permissions for logs are not good. Try to set them again with 

`sudo chmod -R 777 bootstrap/cache storage public/private public/public`

That should help

**Comment by realshadow** [comment]
Closing this for now, since there is no activity. If you need more help feel free to ask
